services:
  - type: web
    name: box-key
    env: node
    rootDir: .
    buildCommand: cd src && npm install
    startCommand: cd src && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_USERNAME
        value: ouriemchiassia0202
      - key: MONGODB_PASSWORD
        value: Mbl44ZYxYpsmWRaZ
      - key: MONGODB_URI
        value: mongodb+srv://ouriemchiassia0202:<ouriemchiassia0202>@box-key.edzawt3.mongodb.net/