services:
  - type: web
    name: box-key
    env: node
    rootDir: .
    buildCommand: cd src && npm install
    startCommand: cd src && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://ouriemchiassia0202:assia@boxkey.cumi44c.mongodb.net/box-key?retryWrites=true&w=majority